production: true
auth:
  url: "http://peatio.app.local/auth/barong"
barong:
  url: "http://barong.app.local"
api:
  url: "http://peatio.app.local/api/v2"
tradePage:
  url: "http://www.app.local/advance"
applogic:
  url: "http://applogic.stage.kayen.io/api/v1"
application_id: "ce0a13ec4b09976a4df33af64514ff75942bae30117e2a4127e866781bcb46da"
blockchainInfoUrl: "https://testnet.blockchain.info/tx/"
currencyFormat: "USD"
currencyName: "US Dollar"
productName: "BCIO"
reCaptchaSiteKey: "6Lf3f3gUAAAAAE0rtFjMhs81Ml1nt-Aa6k2c8fKG"
cookieConfigDomain:
  url: '.app.local'
