version: '3.6'

services:
  frontend:
    image: "${FRONTEND_IMAGE}"
    labels:
      traefik.enable: true
      traefik.frontend.rule: "PathPrefix:/trading;Host:www.${APP_DOMAIN}"
      traefik.port: 3000

  angular:
    image: git.paymium.fr:5001/blockchain.io/bcio-front:develop
    volumes:
      - "${PWD}/config/front_env.yml:/home/node/src/environments/env.yml"
    labels:
      traefik.enable: true
      traefik.frontend.rule: "PathPrefix:/;Host:www.${APP_DOMAIN}"
      traefik.port: 4200
